export const WalletData = [
    {
        key: "1",
        walletID: "D9209DD",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Naira",
        balance: "N24,000",
        dateCreated: "29 Jul, 2024",
        status: "Active",
      },
      {
        key: "2",
        walletID: "JJDD923",
        recentActivity: "Top-Up",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "150 USDT",
        dateCreated: "29 Jul, 2024",
        status: "Deleted",
      },
      {
        key: "3",
        walletID: "D9209DD",
        recentActivity: "Data Purchase",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "212 USDT",
        dateCreated: "29 Jul, 2024",
        status: "Frozen",
      },
      {
        key: "4",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Naira",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Deleted",
      },
      {
        key: "5",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Naira",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Deleted",
      },
      {
        key: "6",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Active",
      },
      {
        key: "7",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Frozen",
      },
      {
        key: "8",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Active",
      },
      {
        key: "9",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Frozen",
      },
      {
        key: "10",
        walletID: "JJDD923",
        recentActivity: "Bet",
        recentDate: "12, August, 2024",
        walletType: "Crypto",
        balance: "N350,000",
        dateCreated: "29 Jul, 2024",
        status: "Active",
      },
    ];