export const RevenueData = [
  {
    key: 1,
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "NGN 32,000",
    method: "Naira",
    user: "@johnkennedy",
    status: "Confirmed",
  },
  {
    key: 2,
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "2400USDT",
    method: "Crypto",
    user: "@johnkennedy",
    status: "Pending",
  },
  {
    key: 3,
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "2400USDT",
    method: "Crypto",
    user: "@johnkennedy",
    status: "Request",
  },
  {
    key: 4, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "NGN 504000",
    method: "Naira",
    user: "@johnkennedy",
    status: "Pending",
  },
  {
    key: 5, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "2400USDT",
    method: "Crypto",
    user: "@johnkennedy",
    status: "Confirmed",
  },
  {
    key: 6, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "NGN 2400",
    method: "Naira",
    user: "@johnkennedy",
    status: "Pending",
  },
  {
    key: 7, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "NGN 4549000",
    method: "Naira",
    user: "@johnkennedy",
    status: "Request",
  },
  {
    key: 8, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "2400USDT",
    method: "Crypto",
    user: "@johnkennedy",
    status: "Pending",
  },
  {
    key: 9, 
    revenueSource: "Bet",
    freeType: "Betting Fee",
    date: "01 Mar, 2024",
    amount: "2400USDT",
    method: "Naira",
    user: "@johnkennedy",
    status: "Confirmed",
  },

  // Add more users as needed
];
