export const SupportData = [
  {
    key: 1,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Closed',
  },
  {
    key: 2,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Open',
  },
  {
    key: 3,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Open',
  },
  {
    key: 4,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Closed',
  },
  {
    key: 5,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Pending',
  },
  {
    key: 6,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Open',
  },
  {
    key: 7,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Pending',
  },
  {
    key: 8,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Open',
  },
  {
    key: 9,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Closed',
  },
  {
    key: 10,
    ticketId: '#23292',
    user: 'Bola John',
    issueType: 'Withdrawal',
    dateCreated: '01 Mar, 2024',
    assignedAdmin: 'Chinozee',
    status: 'Open',
  },
  // Add more users as needed
]
