export const WithdrawalData = [
  {
    key: 1, // Unique key for each user
    name: "Cynthia Boyega",
    username: "@JohnB",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Payout",
  },
  {
    key: 2,
    name: "Sarah Adejoko",
    username: "@JohnB",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "----------",
    status: "Request",
  },
  {
    key: 3,
    name: "John Oke",
    username: "@John",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "---------",
    status: "Request",
  },
  {
    key: 4,
    name: "Faith Chukwu",
    username: "@Faith",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "---------",
    status: "Rejected",
  },
  {
    key: 5,
    name: "Donatus Agukwe",
    username: "@Donatus",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "--------",
    status: "Payout",
  },
  {
    key: 6,
    name: "Ahmed Adam",
    username: "@Ahmed",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Request",
  },
  {
    key: 7,
    name: "Paul Oke",
    username: "@Donatus",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Payout",
  },
  {
    key: 8,
    name: "Ibrahim Sule",
    username: "@Sule",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Rejected",
  },
  {
    key: 9,
    name: "Donus Agukwe",
    username: "@Donatus",
    RequestId: "WCD9283K",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Rejected",
  },
  {
    key: 10,
    name: "Donatus Oke",
    username: "@Donatus",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    Amount: "NGN 32,000",
    payoutId: "23739384",
    status: "Payout",
  },
  // Add more users as needed
];
