export const AdminData = [
  {
    key: 1,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Super Admin",
    status: "Active",
  },
  {
    key: 2,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Admins",
    status: "Active",
  },
  {
    key: 3,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Customer Service",
    status: "Active",
  },
  {
    key: 4,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Admin",
    status: "Active",
  },
  {
    key: 5,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Super Admin",
    status: "Suspended",
  },
  {
    key: 6,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: " Admin",
    status: "Disabled",
  },
  {
    key: 7,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Customer Service",
    status: "Active",
  },
  {
    key: 8,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Admin",
    status: "Suspended",
  },
  {
    key: 9,
    name: "Bola John",
    email: "bolajohn@gmail.com",
    lastLogin: "23 Aug, 2024",
    role: "Super Admin",
    status: "Disabled",
  },
];
