export const usersData = [
  {
    key: 1, // Unique key for each user
    name: "Cynthia Boyega",
    username: "@JohnB",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Verified",
  },
  {
    key: 2,
    name: "Sarah Adejoko",
    username: "@JohnB",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Unverified",
  },
  {
    key: 3,
    name: "John Oke",
    username: "@John",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Deactivated",
  },
  {
    key: 4,
    name: "Faith Chukwu",
    username: "@Faith",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Suspended",
  },
  {
    key: 5,
    name: "Donatus Agukwe",
    username: "@Donatus",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Verified",
  },
  {
    key: 6,
    name: "Ahmed Adam",
    username: "@Ahmed",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Unverified",
  },
  {
    key: 7,
    name: "Paul Oke",
    username: "@Donatus",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Verified",
  },
  {
    key: 8,
    name: "Ibrahim Sule",
    username: "@Sule",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Deactivated",
  },
  {
    key: 9,
    name: "Donus Agukwe",
    username: "@Donatus",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Verified",
  },
  {
    key: 10,
    name: "Donatus Oke",
    username: "@Donatus",
    email: "talk2cynthia@gmail.com",
    date: "01 Mar, 2024",
    activity: "29 Jul, 2024 04:30pm",
    status: "Deactivated",
  },
  // Add more users as needed
];
