export const EventData = [
  {
    key: 1, // Unique key for each user
    name: "Cynthia Boyega",
    username: "@JohnB",
    type: "Football",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jun, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Open",
  },
  {
    key: 2,
    name: "Sarah Adejoko",
    username: "@JohnB",
    type: "Politics",
    Betdate: "29 Jul, 2024",
    Duedate: "29 August, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Closed",
  },
  {
    key: 3,
    name: "John Oke",
    username: "@John",
    type: "Football",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Pending",
  },
  {
    key: 4,
    name: "Faith Chukwu",
    username: "@Faith",
    type: "Sprint",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Closed",
  },
  {
    key: 5,
    name: "Donatus Agukwe",
    username: "@Donatus",
    type: "Basketball",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Pending",
  },
  {
    key: 6,
    name: "Ahmed Adam",
    username: "@Ahmed",
    type: "Volleyball",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Open",
  },
  {
    key: 7,
    name: "Paul Oke",
    username: "@Donatus",
    type: "Football",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Open",
  },
  {
    key: 8,
    name: "Ibrahim Sule",
    username: "@Sule",
    type: "Basketball",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Open",
  },
  {
    key: 9,
    name: "Donus Agukwe",
    username: "@Donatus",
    type: "Sprint",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "open",
  },
  {
    key: 10,
    name: "Donatus Oke",
    username: "@Donatus",
    type: "Politics",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Pending",
  },
  {
    key: 11,
    name: "Donatus Oke",
    username: "@Donatus",
    type: "Politics",
    Betdate: "29 Jul, 2024",
    Duedate: "29 Jul, 2024",
    Amount: "N24,000",
    Bet:  "ManU(W)",
    status: "Waiting",
  },
  // Add more users as needed
];
