export const EventData = [
    {
      key: 1, // Unique key for each user
      betId: "D9209DD",
      participant: "5",
      type: "Football",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jun, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Open",
    },
    {
      key: 2,
      betId: "JJDD923",
      participant: "2",
      type: "Politics",
      Betdate: "29 Jul, 2024",
      Duedate: "29 August, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Closed",
    },
    {
      key: 3,
      betId: "D9209DD",
      participant: "6",
      type: "Football",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Pending",
    },
    {
      key: 4,
      betId: "JJDD923",
      participant: "2",
      type: "Sprint",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Closed",
    },
    {
      key: 5,
      betId: "D9209DD",
      participant: "6",
      type: "Basketball",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Pending",
    },
    {
      key: 6,
      betId: "JJDD923",
      participant: "2",
      type: "Volleyball",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Open",
    },
    {
      key: 7,
      betId: "D9209DD",
      participant: "9",
      type: "Football",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Open",
    },
    {
      key: 8,
      betId: "WEWD923",
      participant: "9",
      type: "Basketball",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Open",
    },
    {
      key: 9,
      betId: "DWDD923",
      participant: "7",
      type: "Sprint",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "open",
    },
    {
      key: 10,
      name: "Donatus Oke",
      username: "@Donatus",
      type: "Politics",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Pending",
    },
    {
      key: 11,
      betId: "D9209DD",
      participant: "5",
      type: "Politics",
      Betdate: "29 Jul, 2024",
      Duedate: "29 Jul, 2024",
      Amount: "N24,000",
      Bet:  "ManU(W)",
      status: "Waiting",
    },
    // Add more users as needed
  ];
  